ARG PYTHON_VERSION=3.12.8
ARG AWS_CLI_VERSION=2.31.19
ARG UV_VERSION=0.9.5
ARG NODE_VERSION=22.21.0

FROM amazon/aws-cli:${AWS_CLI_VERSION} AS aws-cli
FROM ghcr.io/astral-sh/uv:${UV_VERSION} AS uv
FROM node:${NODE_VERSION}-bookworm AS node

FROM python:${PYTHON_VERSION}-bookworm AS python
ARG UV_PROJECT_ENVIRONMENT=/opt/python
ENV PATH=${UV_PROJECT_ENVIRONMENT}/bin:$PATH

FROM python AS builder
COPY --from=uv /uv /uvx /usr/local/bin/
ENV UV_COMPILE_BYTECODE=1
ENV UV_NO_INSTALLER_METADATA=1
ENV UV_LINK_MODE=copy

WORKDIR /source
COPY pyproject.toml uv.lock README.md ./
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=ssh \
    mkdir -p ~/.ssh \
 && ssh-keyscan github.com >> ~/.ssh/known_hosts \
 && uv sync \
    --all-extras \
    --all-groups \
    --locked \
    --no-install-project

FROM python
RUN --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    apt-get update \
 && apt-get install -y --no-install-recommends \
    bash-completion \
    fonts-roboto \
    gh \
    git-lfs \
    graphviz \
    groff \
    jq \
    less \
    locales \
    lsof \
    man \
    nano \
    openssh-client \
    rsync \
    vim \
    zsh \
 && sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen \
 && locale-gen en_US.UTF-8 \
 && git lfs install

ARG DOCKER_VERSION=28.5.1
ARG DOCKER_COMPOSE_VERSION=2.40.1
ARG DIND_FEATURE_VERSION=eea561a9ad45c383c2d9832d2da031410be8b5a0
ARG DOCKER_GID=999
ENV DOCKER_BUILDKIT=1
RUN --mount=type=cache,target=/var/lib/apt/lists,sharing=locked \
    --mount=type=cache,target=/var/cache/apt,sharing=locked \
    apt-get update \
 && curl -fsSL https://raw.githubusercontent.com/devcontainers/features/${DIND_FEATURE_VERSION}/src/docker-in-docker/install.sh \
    | env VERSION=${DOCKER_VERSION} \
    DOCKERDASHCOMPOSEVERSION=${DOCKER_COMPOSE_VERSION} \
    bash \
 && apt-get update # install script clears apt list cache \
 && groupmod -g ${DOCKER_GID} docker

COPY --from=aws-cli /usr/local/aws-cli/v2/current /usr/local
RUN echo "complete -C '/usr/local/bin/aws_completer' aws" >> /etc/bash_completion.d/aws
COPY --from=uv /uv /uvx /usr/local/bin/
RUN echo 'eval "$(uv generate-shell-completion bash)"' >> /etc/bash_completion.d/uv
COPY --from=node /usr/local/bin /usr/local/bin
COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules

RUN echo 'eval "$(uv generate-shell-completion bash)"' >> /etc/bash_completion.d/uv \
 && echo "complete -C '/usr/local/bin/aws_completer' aws" >> /etc/bash_completion.d/aws \
 && docker completion bash > /etc/bash_completion.d/docker \
 && npm install -g @anthropic-ai/claude-code

ARG ECR_CREDENTIAL_HELPER_VERSION=0.10.1
RUN [ $(uname -m) = aarch64 ] && ARCH=arm64 || ARCH=amd64 \
 && curl -fsSL \
    https://amazon-ecr-credential-helper-releases.s3.us-east-2.amazonaws.com/${ECR_CREDENTIAL_HELPER_VERSION}/linux-${ARCH}/docker-credential-ecr-login \
    -o /usr/local/bin/docker-credential-ecr-login \
 && chmod +x /usr/local/bin/docker-credential-ecr-login

ARG APP_USER=metr
ARG APP_DIR=/home/${APP_USER}/app
ARG USER_ID=1000
ARG GROUP_ID=1000
RUN groupadd -g ${GROUP_ID} ${APP_USER} \
 && useradd ${APP_USER} \
    -u ${USER_ID} \
    -g ${APP_USER} \
    -G docker \
    -m \
    -s /bin/bash \
 && mkdir -p \
        /home/${APP_USER}/.aws \
        /home/${APP_USER}/.config/hawk-cli \
        ${APP_DIR} \
 && chown -R ${USER_ID}:${GROUP_ID} \
        /home/${APP_USER} \
        ${APP_DIR}

RUN mkdir -p /home/${APP_USER}/.docker \
 && echo '{"credHelpers": {"328726945407.dkr.ecr.us-west-1.amazonaws.com": "ecr-login", "724772072129.dkr.ecr.us-west-1.amazonaws.com": "ecr-login"}}' > /home/${APP_USER}/.docker/config.json \
 && chown -R ${USER_ID}:${GROUP_ID} /home/${APP_USER}/.docker

COPY --from=builder --chown=${USER_ID}:${GROUP_ID} ${UV_PROJECT_ENVIRONMENT} ${UV_PROJECT_ENVIRONMENT}

WORKDIR ${APP_DIR}
COPY . .
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync \
        --all-extras \
        --all-groups \
        --locked \
 && find ${UV_PROJECT_ENVIRONMENT} -user root -exec chown ${USER_ID}:${GROUP_ID} {} +

ENTRYPOINT ["/usr/local/share/docker-init.sh"]
CMD ["sleep", "infinity"]
